// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHN3YtNFUPcDZy99zLNJnvacRJV5Pb3cs',
    appId: '1:204271193117:web:72ef49f9e3bc07ed488af4',
    messagingSenderId: '204271193117',
    projectId: 'fitflow-cd332',
    authDomain: 'fitflow-cd332.firebaseapp.com',
    storageBucket: 'fitflow-cd332.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnN0B7RwOZWj55a14jTAToGsAEm1uY73k',
    appId: '1:204271193117:android:0b2a591f57439500488af4',
    messagingSenderId: '204271193117',
    projectId: 'fitflow-cd332',
    storageBucket: 'fitflow-cd332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlnO6grDraWixcDJfZ3FSzwluCNxtaQlM',
    appId: '1:204271193117:ios:e7dfca1cd2383b3c488af4',
    messagingSenderId: '204271193117',
    projectId: 'fitflow-cd332',
    storageBucket: 'fitflow-cd332.firebasestorage.app',
    iosClientId: '204271193117-vlc9kll49uhflo5tdt0orl0ra0k7hgg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlnO6grDraWixcDJfZ3FSzwluCNxtaQlM',
    appId: '1:204271193117:ios:e7dfca1cd2383b3c488af4',
    messagingSenderId: '204271193117',
    projectId: 'fitflow-cd332',
    storageBucket: 'fitflow-cd332.firebasestorage.app',
    iosClientId: '204271193117-vlc9kll49uhflo5tdt0orl0ra0k7hgg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHN3YtNFUPcDZy99zLNJnvacRJV5Pb3cs',
    appId: '1:204271193117:web:d6f9c10fa7ac836a488af4',
    messagingSenderId: '204271193117',
    projectId: 'fitflow-cd332',
    authDomain: 'fitflow-cd332.firebaseapp.com',
    storageBucket: 'fitflow-cd332.firebasestorage.app',
  );
}
